services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - .:/src
    restart: always

  mongo:
    image: mongo:latest
    restart: always
    command: ["--replSet", "rs0"]
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mongo-data:
